//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketMVC.Models
{
    using Newtonsoft.Json.Serialization;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKATEGORİLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKATEGORİLER()
        {
            this.TBLÜRÜNLER = new HashSet<TBLÜRÜNLER>();
        }

        public int KATEGORIID { get; set; }

        [StringLength(50, ErrorMessage = "Kategori adı max 50 karakter olabilir.")]
        [Required(ErrorMessage = "Kategori adı boş bırakılamaz.")]
        [DisplayName("Kategori Adı")]
        public string KATEGORIAD { get; set; }

        [DisplayName("Kategori Resim")]
        public string KATEGORIRESIM { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLÜRÜNLER> TBLÜRÜNLER { get; set; }
    }
}
