//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLÜRÜNLER
    {
        public int URUNID { get; set; }

        [Required(ErrorMessage = "Ürün adı boş bırakılamaz.")]
        [StringLength(50, ErrorMessage = "Ürün adı max 50 karakter olmalıdır.")]
        [DisplayName("Ürün Adı")]
        public string URUNAD { get; set; }

        [Required(ErrorMessage = "Lütfen kategori seçiniz.")]
        [DisplayName("Kategori")]
        public Nullable<int> KATEGORIID { get; set; }

        [Required(ErrorMessage = "Birim boş bırakılamaz.")]
        [StringLength(20, ErrorMessage = "Birim max 20 karakter olmalıdır.")]
        [DisplayName("Birim")]
        public string URUNBIRIM { get; set; }

        [Required(ErrorMessage = "Ürün fiyatı boş bırakılamaz.")]
        [DisplayName("Fiyat")]
        public Nullable<decimal> URUNFIYAT { get; set; }

        [DisplayName("Ürün Resim")]
        public string URUNRESIM { get; set; }

        [DisplayName("İndirim Oranı (%)")]
        public Nullable<int> URUNINDIRIMORANI { get; set; }

        public virtual TBLKATEGORİLER TBLKATEGORİLER { get; set; }
    }
}
